#!/bin/bash

echo -e "\n################## CASE 1 ##################\n"

echo "/bin/ls -l" | /bin/sh > ../outsh
echo "/bin/ls -l" | ./hsh > ../outhsh
diff ../outsh ../outhsh > ../Task5_1

rm ../outsh
rm ../outhsh

if [ -s ../Task5_1 ]
then
	printf "error on '/bin/ls -l' command\n"
else
	rm -rf ../Task5_1
	printf "Success on '/bin/ls -l' command\n"
fi


echo -e "\n################## CASE 2 ##################\n"

echo "/bin/ls                 -la" | /bin/sh > ../outsh
echo "/bin/ls                 -la" | ./hsh > ../outhsh
diff ../outsh ../outhsh > ../Task5_1

rm ../outsh
rm ../outhsh

if [ -s ../Task5_1 ]
then
	printf "error on '/bin/ls       -la' command\n"
else
	rm -rf ../Task5_1
	printf "Success on '/bin/ls     -la' command\n"
fi

echo -e "\n################## CASE 3 ##################\n"

echo "/bin/ls p" | /bin/sh > ../outsh
echo "/bin/ls p" | ./hsh > ../outhsh
diff ../outsh ../outhsh > ../Task5_1

rm ../outsh
rm ../outhsh

if [ -s ../Task5_1 ]
then
	printf "error on '/bin/ls p' command\n"
else
	rm -rf ../Task5_1
	printf "Success on '/bin/ls p' command\n"
fi

echo -e "\n################## CASE 4 ##################\n"

echo "/bin/ls\0 -l" | /bin/sh > ../outsh
echo "/bin/ls\0 -l" | ./hsh > ../outhsh
diff ../outsh ../outhsh > ../Task5_1

rm ../outsh
rm ../outhsh

if [ -s ../Task5_1 ]
then
	printf "Error on '/bin/ls\0 -l' command\n"
else
	rm -rf ../Task5_1
	printf "Success on '/bin/ls\0 -l' command\n"
fi


echo -e "\n################## CASE 5 ##################\n"
echo -e "##################dot-space-dot##################\n"

echo "./hsh: 1: .: .: not found" > ../outsh
echo ".  ." | ./hsh 2> ../outhsh

diff ../outsh ../outhsh > ../Task5_1



if [ -s ../Task5_1 ]
then
	printf "incorrect output  - FAIL\n"
	printf "output must be: \n"
	printf "./hsh: 1: .: .: not found\n"
	printf "actual output:\n"
	echo ".  ." | ./hsh 
else
	rm -rf ../Task5_1
	printf "correct output  - SUCCESS\n"
	printf "actual output:\n"
	echo ".  ." | ./hsh
fi

echo -e "\n################## CASE 6 ##################\n"
echo -e "##################space-space-dot##################\n"

echo "  ." | /bin/sh 2> ../outsh
echo "  ." | ./hsh 2> ../outhsh

diff ../outsh ../outhsh > ../Task5_1



if [ -s ../Task5_1 ]
then
	printf "incorrect output  - FAIL\n"
	printf "output must be: \n"
	echo "  ." | /bin/sh
	printf "actual output:\n"
	echo "  ." | ./hsh 
else
	rm -rf ../Task5_1
	printf "correct output  - SUCCESS\n"
	printf "actual output:\n"
	echo "  ." | ./hsh
fi


echo -e "\n################## CASE 7 ##################\n"
echo -e "##################space-dot-dot##################\n"

echo "./hsh: 1: ..: Permission denied" > ../outsh
echo " .." | ./hsh 2> ../outhsh

diff ../outsh ../outhsh > ../Task5_1



if [ -s ../Task5_1 ]
then
	printf "incorrect output  - FAIL\n"
	printf "output must be: \n"
	printf "./hsh: 1: ..: Permission denied"
	printf "actual output:\n"
	echo " .." | ./hsh 
else
	rm -rf ../Task5_1
	printf "correct output  - SUCCESS\n"
	printf "actual output:\n"
	echo " .." | ./hsh
fi

echo -e "\n################## CASE 8 ##################\n"
echo -e "##################incorrect function##################\n"

echo "./hsh: 1: ffh: not found" > ../outsh
echo "ffh" | ./hsh 2> ../outhsh

diff ../outsh ../outhsh > ../Task5_1



if [ -s ../Task5_1 ]
then
	printf "incorrect output  - FAIL\n"
	printf "command used: ffh\n"
	printf "output must be: \n"
	printf "./hsh: 1: ffh: not found"
	printf "actual output:\n"
	echo "ffh" | ./hsh 
else
	rm -rf ../Task5_1
	printf "correct output  - SUCCESS\n"
	printf "actual output:\n"
	echo "ffh" | ./hsh
fi

echo -e "\n################## CASE 9 ##################\n"
echo -e "##################incorrect flag##################\n"

echo "ls dfg" | /bin/sh 2> ../outsh
echo "ls dfg" | ./hsh 2> ../outhsh

diff ../outsh ../outhsh > ../Task5_1



if [ -s ../Task5_1 ]
then
	printf "incorrect output  - FAIL\n"
	printf "command used: ls dfg\n"
	printf "output must be: \n"
	echo "ls dfg" | /bin/sh
	printf "actual output:\n"
	echo "ls dfg" | ./hsh 
else
	rm -rf ../Task5_1
	printf "correct output  - SUCCESS\n"
	printf "actual output:\n"
	echo "ls dfg" | ./hsh
fi